// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Annealer

#ifndef _ANNEALER_UI_H
#define _ANNEALER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_mainscreen
void ui_mainscreen_screen_init(void);
extern lv_obj_t *ui_mainscreen;
void ui_event_BtnAuto( lv_event_t * e);
extern lv_obj_t *ui_BtnAuto;
extern lv_obj_t *ui_BtnAutoLabel;
extern lv_obj_t *ui_Temp;
extern lv_obj_t *ui_TempLabel;
extern lv_obj_t *ui_Amps;
extern lv_obj_t *ui_AmpsLabel;
void ui_event_BtnManual( lv_event_t * e);
extern lv_obj_t *ui_BtnManual;
extern lv_obj_t *ui_BtnManualLabel;
extern lv_obj_t *ui_State;
void ui_event_SliderAnnealTime( lv_event_t * e);
extern lv_obj_t *ui_SliderAnnealTime;
extern lv_obj_t *ui_AnnealTime;
void ui_event_SliderPauseTime( lv_event_t * e);
extern lv_obj_t *ui_SliderPauseTime;
extern lv_obj_t *ui_PauseTime;
extern lv_obj_t *ui_Count;
extern lv_obj_t *ui_CountLabel;
void ui_event_BtnReset( lv_event_t * e);
extern lv_obj_t *ui_BtnReset;
extern lv_obj_t *ui_BtnResetLabel;
extern lv_obj_t *ui____initial_actions0;

// My main project hooks
void handlePauseSliderEvent(lv_event_t * e);
void handleAnnealSliderEvent(lv_event_t * e);
void handleAutoBtnEvent(lv_event_t * e);
void handleManualBtnEvent(lv_event_t * e);
void handleResetBtnEvent(lv_event_t * e);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
