// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Annealer

#ifndef _UI_COMP_BTNAUTOLBL_H
#define _UI_COMP_BTNAUTOLBL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BtnAutoLbl
#define UI_COMP_BTNAUTOLBL_BTNAUTOLBL 0
#define _UI_COMP_BTNAUTOLBL_NUM 1
lv_obj_t *ui_BtnAutoLbl_create(lv_obj_t *comp_parent);
void ui_event_comp_BtnAutoLbl_BtnAutoLbl( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
