// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Annealer

#include "ui.h"

void annealTimeSliderChangedFn(lv_event_t * e)
{
	handleAnnealSliderEvent(e);
}

void autoBtnFn(lv_event_t * e)
{
	handleAutoBtnEvent(e);
}

void manualBtnFn(lv_event_t * e)
{
	handleManualBtnEvent(e);
}

void SliderAnnealTimeChangedFn(lv_event_t * e)
{
  handleAnnealSliderEvent(e);
}

void SliderPauseTimeChangedFn(lv_event_t * e)
{
  handlePauseSliderEvent(e);
}

void resetBtnFn(lv_event_t * e)
{
	handleResetBtnEvent(e);
}
