// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Annealer

#include "ui.h"

void ui_SplashScreen_screen_init(void)
{
ui_SplashScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Logo = lv_img_create(ui_SplashScreen);
lv_img_set_src(ui_Logo, &ui_img_stallionarms_240x99_png);
lv_obj_set_width( ui_Logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Logo, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SplashVersion = lv_label_create(ui_SplashScreen);
lv_obj_set_width( ui_SplashVersion, 200);
lv_obj_set_height( ui_SplashVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SplashVersion, 0 );
lv_obj_set_y( ui_SplashVersion, 18 );
lv_obj_set_align( ui_SplashVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_SplashVersion,"Version 0.9.0");
lv_obj_set_style_text_color(ui_SplashVersion, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SplashVersion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SplashVersion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SplashVersion, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SplashTitle = lv_label_create(ui_SplashScreen);
lv_obj_set_width( ui_SplashTitle, 200);
lv_obj_set_height( ui_SplashTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SplashTitle, 0 );
lv_obj_set_y( ui_SplashTitle, -12 );
lv_obj_set_align( ui_SplashTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SplashTitle,"Auto Annealer");
lv_obj_set_style_text_color(ui_SplashTitle, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SplashTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SplashTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SplashTitle, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner = lv_spinner_create(ui_SplashScreen,1000,90);
lv_obj_set_width( ui_Spinner, 50);
lv_obj_set_height( ui_Spinner, 50);
lv_obj_set_x( ui_Spinner, 0 );
lv_obj_set_y( ui_Spinner, 98 );
lv_obj_set_align( ui_Spinner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags


}
