// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Annealer

#include "ui.h"

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSettingsCancel = lv_btn_create(ui_SettingsScreen);
lv_obj_set_width( ui_BtnSettingsCancel, 80);
lv_obj_set_height( ui_BtnSettingsCancel, 35);
lv_obj_set_x( ui_BtnSettingsCancel, -64 );
lv_obj_set_y( ui_BtnSettingsCancel, 131 );
lv_obj_set_align( ui_BtnSettingsCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSettingsCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSettingsCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSettingsCancel, lv_color_hex(0x0040C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSettingsCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSettingsCancelLabel = lv_label_create(ui_BtnSettingsCancel);
lv_obj_set_width( ui_BtnSettingsCancelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnSettingsCancelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnSettingsCancelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnSettingsCancelLabel,"Cancel");
lv_obj_set_style_text_color(ui_BtnSettingsCancelLabel, lv_color_hex(0xFCE200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnSettingsCancelLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnSettingsCancelLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSettingsSave = lv_btn_create(ui_SettingsScreen);
lv_obj_set_width( ui_BtnSettingsSave, 80);
lv_obj_set_height( ui_BtnSettingsSave, 35);
lv_obj_set_x( ui_BtnSettingsSave, 59 );
lv_obj_set_y( ui_BtnSettingsSave, 130 );
lv_obj_set_align( ui_BtnSettingsSave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSettingsSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSettingsSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSettingsSave, lv_color_hex(0x0040C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSettingsSave, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnSettingsSave, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_BtnSettingsSave, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_BtnSettingsSaveLabel = lv_label_create(ui_BtnSettingsSave);
lv_obj_set_width( ui_BtnSettingsSaveLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnSettingsSaveLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnSettingsSaveLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnSettingsSaveLabel,"Save");
lv_obj_set_style_text_color(ui_BtnSettingsSaveLabel, lv_color_hex(0xFCE200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnSettingsSaveLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnSettingsSaveLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderFeederDwellTime = lv_slider_create(ui_SettingsScreen);
lv_slider_set_range(ui_SliderFeederDwellTime, 5,20);
lv_slider_set_value( ui_SliderFeederDwellTime, 10, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderFeederDwellTime)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderFeederDwellTime, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderFeederDwellTime, 210);
lv_obj_set_height( ui_SliderFeederDwellTime, 20);
lv_obj_set_x( ui_SliderFeederDwellTime, -8 );
lv_obj_set_y( ui_SliderFeederDwellTime, -143 );
lv_obj_set_align( ui_SliderFeederDwellTime, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderFeederDwellTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderFeederDwellTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderFeederDwellTime, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderFeederDwellTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderFeederDwellTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderFeederDwellTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_SliderFeederDwellTime, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderFeederDwellTime, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderFeederDwellTime, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderFeederDwellTime, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderFeederDwellTime, lv_color_hex(0x0042C3), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderFeederDwellTime, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SliderFeederDwellTime, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SliderFeederDwellTime, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SliderFeederDwellTime, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SliderFeederDwellTime, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderFeederDwellTime, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderFeederDwellTime, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderFeederDwellTime, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderFeederDwellTime, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_FeederDwellTime = lv_label_create(ui_SliderFeederDwellTime);
lv_obj_set_width( ui_FeederDwellTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FeederDwellTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FeederDwellTime, -108 );
lv_obj_set_y( ui_FeederDwellTime, -1 );
lv_obj_set_align( ui_FeederDwellTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_FeederDwellTime,"1.0");
lv_obj_set_style_text_color(ui_FeederDwellTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FeederDwellTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FeederDwellTime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FeederDwellTimeLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_FeederDwellTimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FeederDwellTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FeederDwellTimeLabel, -70 );
lv_obj_set_y( ui_FeederDwellTimeLabel, -127 );
lv_obj_set_align( ui_FeederDwellTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FeederDwellTimeLabel,"Feeder Dwell (s)");
lv_obj_set_style_text_color(ui_FeederDwellTimeLabel, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FeederDwellTimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FeederDwellTimeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FeederDwellTimeLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderDropDwellTime = lv_slider_create(ui_SettingsScreen);
lv_slider_set_range(ui_SliderDropDwellTime, 0,100);
lv_slider_set_value( ui_SliderDropDwellTime, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderDropDwellTime)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderDropDwellTime, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderDropDwellTime, 210);
lv_obj_set_height( ui_SliderDropDwellTime, 20);
lv_obj_set_x( ui_SliderDropDwellTime, -8 );
lv_obj_set_y( ui_SliderDropDwellTime, -101 );
lv_obj_set_align( ui_SliderDropDwellTime, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderDropDwellTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderDropDwellTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderDropDwellTime, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderDropDwellTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderDropDwellTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderDropDwellTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_SliderDropDwellTime, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderDropDwellTime, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderDropDwellTime, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderDropDwellTime, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderDropDwellTime, lv_color_hex(0x0042C3), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderDropDwellTime, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SliderDropDwellTime, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SliderDropDwellTime, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SliderDropDwellTime, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SliderDropDwellTime, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderDropDwellTime, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderDropDwellTime, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderDropDwellTime, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderDropDwellTime, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_DropDwellTime = lv_label_create(ui_SliderDropDwellTime);
lv_obj_set_width( ui_DropDwellTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DropDwellTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropDwellTime, -108 );
lv_obj_set_y( ui_DropDwellTime, -3 );
lv_obj_set_align( ui_DropDwellTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_DropDwellTime,"000");
lv_obj_set_style_text_color(ui_DropDwellTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DropDwellTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DropDwellTime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DropDwellTimeLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_DropDwellTimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DropDwellTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropDwellTimeLabel, -74 );
lv_obj_set_y( ui_DropDwellTimeLabel, -87 );
lv_obj_set_align( ui_DropDwellTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DropDwellTimeLabel,"Drop Offset");
lv_obj_set_style_text_color(ui_DropDwellTimeLabel, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DropDwellTimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DropDwellTimeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DropDwellTimeLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderMotorSpeed = lv_slider_create(ui_SettingsScreen);
lv_slider_set_range(ui_SliderMotorSpeed, 10,50);
lv_slider_set_value( ui_SliderMotorSpeed, 30, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderMotorSpeed)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderMotorSpeed, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderMotorSpeed, 210);
lv_obj_set_height( ui_SliderMotorSpeed, 20);
lv_obj_set_x( ui_SliderMotorSpeed, -8 );
lv_obj_set_y( ui_SliderMotorSpeed, -60 );
lv_obj_set_align( ui_SliderMotorSpeed, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderMotorSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMotorSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMotorSpeed, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMotorSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMotorSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMotorSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_SliderMotorSpeed, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderMotorSpeed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderMotorSpeed, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderMotorSpeed, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderMotorSpeed, lv_color_hex(0x0042C3), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMotorSpeed, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SliderMotorSpeed, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SliderMotorSpeed, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SliderMotorSpeed, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SliderMotorSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMotorSpeed, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMotorSpeed, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMotorSpeed, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMotorSpeed, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MotorSpeed = lv_label_create(ui_SliderMotorSpeed);
lv_obj_set_width( ui_MotorSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MotorSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MotorSpeed, -108 );
lv_obj_set_y( ui_MotorSpeed, -3 );
lv_obj_set_align( ui_MotorSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_MotorSpeed,"300");
lv_obj_set_style_text_color(ui_MotorSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MotorSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MotorSpeed, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MotorSpeedLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_MotorSpeedLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MotorSpeedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MotorSpeedLabel, -79 );
lv_obj_set_y( ui_MotorSpeedLabel, -45 );
lv_obj_set_align( ui_MotorSpeedLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MotorSpeedLabel,"Speed");
lv_obj_set_style_text_color(ui_MotorSpeedLabel, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MotorSpeedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MotorSpeedLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MotorSpeedLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderMotorCurrent = lv_slider_create(ui_SettingsScreen);
lv_slider_set_range(ui_SliderMotorCurrent, 5,20);
lv_slider_set_value( ui_SliderMotorCurrent, 12, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderMotorCurrent)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderMotorCurrent, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderMotorCurrent, 210);
lv_obj_set_height( ui_SliderMotorCurrent, 20);
lv_obj_set_x( ui_SliderMotorCurrent, -8 );
lv_obj_set_y( ui_SliderMotorCurrent, -18 );
lv_obj_set_align( ui_SliderMotorCurrent, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderMotorCurrent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMotorCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMotorCurrent, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMotorCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMotorCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMotorCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_SliderMotorCurrent, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderMotorCurrent, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderMotorCurrent, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderMotorCurrent, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderMotorCurrent, lv_color_hex(0x0042C3), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMotorCurrent, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SliderMotorCurrent, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SliderMotorCurrent, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SliderMotorCurrent, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SliderMotorCurrent, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMotorCurrent, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMotorCurrent, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMotorCurrent, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMotorCurrent, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MotorCurrent = lv_label_create(ui_SliderMotorCurrent);
lv_obj_set_width( ui_MotorCurrent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MotorCurrent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MotorCurrent, -108 );
lv_obj_set_y( ui_MotorCurrent, -3 );
lv_obj_set_align( ui_MotorCurrent, LV_ALIGN_CENTER );
lv_label_set_text(ui_MotorCurrent,"1.2");
lv_obj_set_style_text_color(ui_MotorCurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MotorCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MotorCurrent, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MotorCurrentLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_MotorCurrentLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MotorCurrentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MotorCurrentLabel, -83 );
lv_obj_set_y( ui_MotorCurrentLabel, -3 );
lv_obj_set_align( ui_MotorCurrentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MotorCurrentLabel,"Current (A)");
lv_obj_set_style_text_color(ui_MotorCurrentLabel, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MotorCurrentLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MotorCurrentLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MotorCurrentLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderMaxTemp = lv_slider_create(ui_SettingsScreen);
lv_slider_set_range(ui_SliderMaxTemp, 100,200);
lv_slider_set_value( ui_SliderMaxTemp, 125, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderMaxTemp)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderMaxTemp, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderMaxTemp, 210);
lv_obj_set_height( ui_SliderMaxTemp, 20);
lv_obj_set_x( ui_SliderMaxTemp, -8 );
lv_obj_set_y( ui_SliderMaxTemp, 23 );
lv_obj_set_align( ui_SliderMaxTemp, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderMaxTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMaxTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMaxTemp, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMaxTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMaxTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMaxTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_SliderMaxTemp, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderMaxTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderMaxTemp, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderMaxTemp, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderMaxTemp, lv_color_hex(0x0042C3), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMaxTemp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SliderMaxTemp, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SliderMaxTemp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SliderMaxTemp, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SliderMaxTemp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMaxTemp, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMaxTemp, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMaxTemp, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMaxTemp, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MaxTemp = lv_label_create(ui_SliderMaxTemp);
lv_obj_set_width( ui_MaxTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MaxTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MaxTemp, -108 );
lv_obj_set_y( ui_MaxTemp, -3 );
lv_obj_set_align( ui_MaxTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_MaxTemp,"125");
lv_obj_set_style_text_color(ui_MaxTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MaxTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MaxTemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MaxTempLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_MaxTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MaxTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MaxTempLabel, -77 );
lv_obj_set_y( ui_MaxTempLabel, 38 );
lv_obj_set_align( ui_MaxTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MaxTempLabel,"Hi Temp (F)");
lv_obj_set_style_text_color(ui_MaxTempLabel, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MaxTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MaxTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MaxTempLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderMinTemp = lv_slider_create(ui_SettingsScreen);
lv_slider_set_range(ui_SliderMinTemp, 75,150);
lv_slider_set_value( ui_SliderMinTemp, 95, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderMinTemp)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderMinTemp, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderMinTemp, 210);
lv_obj_set_height( ui_SliderMinTemp, 20);
lv_obj_set_x( ui_SliderMinTemp, -8 );
lv_obj_set_y( ui_SliderMinTemp, 65 );
lv_obj_set_align( ui_SliderMinTemp, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderMinTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMinTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMinTemp, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMinTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMinTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMinTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_SliderMinTemp, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderMinTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderMinTemp, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderMinTemp, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderMinTemp, lv_color_hex(0x0042C3), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderMinTemp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SliderMinTemp, lv_color_hex(0x2095F6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SliderMinTemp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SliderMinTemp, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SliderMinTemp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SliderMinTemp, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SliderMinTemp, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SliderMinTemp, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SliderMinTemp, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MinTemp = lv_label_create(ui_SliderMinTemp);
lv_obj_set_width( ui_MinTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinTemp, -108 );
lv_obj_set_y( ui_MinTemp, -3 );
lv_obj_set_align( ui_MinTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinTemp,"95");
lv_obj_set_style_text_color(ui_MinTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinTemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinTempLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_MinTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinTempLabel, -78 );
lv_obj_set_y( ui_MinTempLabel, 80 );
lv_obj_set_align( ui_MinTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinTempLabel,"Low Temp (F)");
lv_obj_set_style_text_color(ui_MinTempLabel, lv_color_hex(0x00C1DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MinTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinTempLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BtnSettingsCancel, ui_event_BtnSettingsCancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSettingsSave, ui_event_BtnSettingsSave, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderFeederDwellTime, ui_event_SliderFeederDwellTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderDropDwellTime, ui_event_SliderDropDwellTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderMotorSpeed, ui_event_SliderMotorSpeed, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderMotorCurrent, ui_event_SliderMotorCurent, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderMaxTemp, ui_event_SliderMaxTemp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderMinTemp, ui_event_SliderMinTemp, LV_EVENT_ALL, NULL);

}
